name: Pipeline Proiect Final  # Numele care apare in tab-ul Actions

on:
  push:
    branches: [ main ]  # Pipeline-ul porneste doar cand trimiti cod pe ramura principala

jobs:
  # JOB 1: Testarea (Aici verificam daca "decolarea" e sigura)
  test:
    runs-on: ubuntu-latest # Robotul foloseste un sistem Linux de la GitHub
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Copiaza codul tau pe serverul lor

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Maven Tests
        run: mvn test # Aceasta este comanda ceruta. Va rula chiar daca nu avem cod Java inca.